sudo: required
language: java
jdk:
- openjdk8
env:
  global:
  - SERVICE_PORT=8080
  - IMAGE_NAME=greeting
  - COMMIT=${TRAVIS_COMMIT::8}
  - RELEASE_NAME=cloudnativesampleapp
  - DOCKER_REPO=ibmcase
stages:
- local build and test
- docker build, deploy, and test
jobs:
  include:
  - stage: local build and test
    script:
    - mvn install
    - java -jar ./target/cloudnativesampleapp-1.0-SNAPSHOT.jar &
    - bash scripts/health_check.sh
    - bash scripts/api_tests.sh 127.0.0.1 ${SERVICE_PORT}
  - stage: docker build, deploy, and test
    services:
    - docker
    install:
    - true
    script:
    - docker build -f Dockerfile.multistage -t $IMAGE_NAME:$COMMIT .
    - docker run --net=host --name ${RELEASE_NAME} -d -p ${SERVICE_PORT}:${SERVICE_PORT}
      "$IMAGE_NAME:$COMMIT"
    - docker ps
    - docker logs -f ${RELEASE_NAME} &
    - bash scripts/health_check.sh
    - bash scripts/api_tests.sh 127.0.0.1 ${SERVICE_PORT}
    - docker images
    - docker tag $IMAGE_NAME:$COMMIT $DOCKER_REPO/$IMAGE_NAME:$COMMIT
    - docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - docker push $DOCKER_REPO/$IMAGE_NAME:$COMMIT
